dist: trusty
sudo: false

language: node_js
node_js:
    - '10'

cache:
    directories:
        - ./node_modules

before_install:
        - travis_retry sudo apt-get update
        - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq libavahi-compat-libdnssd-dev

install:
    - npm install

jobs:
    include:
        - stage: lint
          if: branch = master
          name: 'Linting Application ...'
          script: npm run lint
        - stage: build
          if: type = push AND branch != master OR type = pull_request
          name: 'Building Application ...'
          script: npm run ng:build
        - stage: build
          if: type = push AND branch = master
          name: 'Building Application ...'
          script: npm run pack
