dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

before_deploy:
  - git config --global user.email "timon.gaebelein@icloud.com"
  - git config --global user.name "UnchartedBull"
  - git config --global push.default matching
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/package
  - mv $TRAVIS_BUILD_DIR/package/*armv7l.deb $TRAVIS_BUILD_DIR/OctoDash_$(git describe --tags $(git rev-list --tags --max-count=1))_armv7l.deb
  - mv $TRAVIS_BUILD_DIR/package/*arm64.deb $TRAVIS_BUILD_DIR/OctoDash_$(git describe --tags $(git rev-list --tags --max-count=1))_arm64.deb

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      name: "Linting Angular Application ..."
      script: ng lint
    - stage: build
      if: type = pull_request
      name: "Building Angular Application ..."
      script: npm run ng:build
    - stage: build
      if: type = push AND branch = master
      name: "Packaging Electron App ..."
      script: npm run pack
    - stage: deploy
      if: type = push AND branch = master
      name: "Deploying the GitHub Releases ..."
      deploy:
        provider: script
        skip_cleanup: true
        script: .travis/bump_version.sh
        on:
          branch: master
          tags: false
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        draft: true
        file_glob: true
        file:
          - "OctoDash_*_armv7l.deb"
          - "OctoDash_*_arm64.deb"
